### ISSUE TITLE
[BATCH] Variable not highlighted

### ISSUE THREAD

**Issue by nolme** [SeanCline/Npp-VS2012-Dark#11]
On my batch file, variables using % or ! are not highlighted.
![20151103125655](https://cloud.githubusercontent.com/assets/4461224/10907466/9a076614-822a-11e5-954b-aa38eea49466.jpg)

**Comment by SeanCline** [comment]
Unfortunately Visual Studio doesn't highlight .bat files at all for me to steal how it does it. (Which is why I left it pretty plain.)
I just changed it to use the same light-blue that studio uses for XML attributes. It should stand out enough.
![2015-11-03 08_37_54-c__users_majin_desktop_blah bat - notepad](https://cloud.githubusercontent.com/assets/3418587/10909327/5b14e8f6-8206-11e5-849f-22576f6109b5.png)
