### ISSUE TITLE
Adding Typescript Support

### ISSUE THREAD

**Issue by shameerkc** [SeanCline/Npp-VS2012-Dark#19]
Is it possible to add typescript support also?

I used https://github.com/sorskoot/npp-typescript-vs while working on a typescript project and if possible, please add to the master..

[TypeScript-VSLight.xml.txt](https://github.com/SeanCline/Npp-VS2012-Dark/files/140119/TypeScript-VSLight.xml.txt)

**Comment by SeanCline** [comment]
Sorry about the delay. I've had pretty good luck just using the javascript syntax highlighting with typescript files. Since I've added the ES6 keywords, and typescript shares most of them, it looks pretty good.

Can you give that a try? I'd rather just make use of what is already there than to add a user-defined language.

**Comment by shameerkc** [comment]
Thanks Sean... it works perfect :)

**Comment by shameerkc** [comment]
Just realized that both issues are fixed in [this fork](https://github.com/Nidre/VS2015-Dark-Npp)
