### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by andrei3pillarglobal** [SeanCline/Npp-VS2012-Dark#5]
I get a error when loading the skin in notepad++
it say: "Load stylers.xml failed!"

**Comment by SeanCline** [comment]
This usually happens if you "Right Click->Save Link As" on VS2012-Dark.xml in the file list. The saved file ends up having some extra html around the contents.

Make sure you get the raw version of the file: [https://raw.githubusercontent.com/SeanCline/Npp-VS2012-Dark/master/VS2012-Dark.xml](https://raw.githubusercontent.com/SeanCline/Npp-VS2012-Dark/master/VS2012-Dark.xml)

Let me know if that takes care of the problem.

**Comment by andrei3pillarglobal** [comment]
Thank you, it worked.
